### ISSUE TITLE
Getting jscoverage_report is not defined for https url in WebDriverGeneralProxyTest

### ISSUE THREAD

**Issue by mayankdevapplift** [tntim96/JSCover-samples#4] opened 2017-07-02 19:22 UTC
I have to calculate the code coverage of an app in which I want to access the url which is ssl enabled. Is there any way to do this?
Currently I am getting jscoverage_report is not defined

**Comment by tntim96** [comment] 2017-07-03 03:17
Duplicate of https://github.com/tntim96/JSCover/issues/254

**Closed by tntim96** 2017-07-03 03:17 UTC
Labels: question
